### ISSUE TITLE
Docker環境でSystem Specが動作するようにする

### ISSUE THREAD

**Issue by okuramasafumi** [mitakarb/beerkeeper#105]
`Selenium`とかを入れないとだめっぽい。
最近だとPlaywrightっていうのもあるみたいなので、そちらを試すのもアリかも？
https://github.com/microsoft/playwright
Ruby向けドライバもあります。
https://github.com/YusukeIwaki/playwright-ruby-client

**Comment by tatsuosakurai** [comment]
今は動くようになったのでクローズ！
