### ISSUE TITLE
ユーザーがイベントに参加できるようにする

### ISSUE THREAD

**Issue by shioimm** [mitakarb/beerkeeper#27]
### やりたいこと
- 既存のイベントに対してユーザーが参加できるようにしたい

### TODO
- イベント参加のためのテーブルを作る
- イベント参加のためのコントローラーを作る
- app/views/events/show.html.himlに参加ボタンを追加

**Comment by shioimm** [comment]
### リソース設計の話
- 参照: [13回目:20200813](https://mitakarb.esa.io/posts/21)
- Userの主催しているイベント -> 主催イベント・参加イベントの二種類
    - `has_many :organizing_events ` -> 主催しているイベント(済) #36 
    - `has_many :paticipating_events(仮), through: :参加テーブル` -> 参加しているイベント 
      - 参加テーブルはまだないので作らないといけない…  
- ルートを整備する
    - `/events?filter=organizing` -> 主催イベント一覧
    - `/events?filter=attending?` -> 参加イベント一覧

**Comment by tatsuosakurai** [comment]
今はできてるのでクローズ
