### ISSUE TITLE
イベントの参加費欄に数値以外が入力できてしまう

### ISSUE THREAD

**Issue by a5-stable** [mitakarb/beerkeeper#736]
例
<img width="891" alt="Screenshot 2024-03-14 at 21 19 06" src="https://github.com/mitakarb/beerkeeper/assets/52599949/dff88ca7-3eb4-45fb-8bc5-37ecf81f0e01">

**Comment by OdenTakashi** [comment]
[budget が string なんでだっけ？\- 「だいたい5千円くらい」とか色々書けそう](https://mitakarb.esa.io/posts/10)

イベントの参加費欄には数値以外も欲しい場合があるため、closeします。
