### ISSUE TITLE
dependabotのPR、CI通ったらマージされるようにしたい

### ISSUE THREAD

**Issue by tatsuosakurai** [mitakarb/beerkeeper#792]
基本やらない設定だと思うけど、小さいアプリだし、チャレンジしたい
(手動でポチポチがめんどくなってきた...)

**Comment by YutaGoto** [comment]
このあたりの設定ができればいけそうです。。
https://docs.github.com/ja/code-security/dependabot/working-with-dependabot/automating-dependabot-with-github-actions#enable-auto-merge-on-a-pull-request
